import type { Metadata } from "next";
import { Fira_Code, Outfit, Titillium_Web } from "next/font/google";
import { ThemeProvider } from "@/lib/providers/ThemeProvider";
import { Header } from "@/lib/ui/Layout/Header/Header";
import "@cubicsui/components/styles.css";
import "@cubicsui/icons/animations.css";
import "./globals.css";

export const firaCode = Fira_Code({
  variable: "--font-code",
  weight: ["300", "500"],
  subsets: ["latin"],
  display: "swap",
});
export const outfit = Outfit({
  variable: "--font-h",
  weight: ["300", "500"],
  subsets: ["latin"],
  display: "swap",
});
export const titiliumWeb = Titillium_Web({
  variable: "--font-p",
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Cubics UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${titiliumWeb.variable} ${firaCode.variable}`}
      >
        <ThemeProvider enableSystem>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
